name: clean_app
description: Base Architecture to continious development.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # GetX
  # https://pub.dev/packages/get
  get: ^4.6.5

  # Equatable
  # https://pub.dev/packages/equatable
  equatable: ^2.0.3

  # Intl
  # https://pub.dev/packages/intl
  intl: ^0.17.0

  # Flutter Native Splash
  # https://pub.dev/packages/flutter_native_splash
  flutter_native_splash: ^1.3.1

  # Flutter SVG
  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^1.0.0

  # Flutter SVG
  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.0.17

  # Flutter Https
  # https://pub.dev/packages/http
  http: ^0.13.4

  # Flutter Dio Services
  # https://pub.dev/packages/dio
  dio: ^4.0.4

  # SharedPreferences
  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.0.11

  # Display QR
  # https://pub.dev/packages/qr_flutter
  qr_flutter: ^4.0.0

  # Scannable QR
  # https://pub.dev/packages/qr_code_scanner
  qr_code_scanner: ^1.0.0

  # Scan QR
  # https://pub.dev/packages/flutter_barcode_scanner
  flutter_barcode_scanner: ^2.0.0

  # TypeAhead
  # https://pub.dev/packages/flutter_typeahead
  flutter_typeahead: ^4.0.0

  # Calendar Sync
  # https://pub.dev/packages/syncfusion_flutter_datepicker
  syncfusion_flutter_datepicker: ^19.4.38

  # Image Picker
  image_picker: ^0.8.4+4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
